### ISSUE TITLE
find a nice way to display parameters

### ISSUE THREAD

**Issue by wen-jams** [wen-jams/bsavi#1]
probably using holoviews
make contour reflect if a certain variable is increasing or decreasing if you move along a certain direction within the contour. perhaps making the contour colored so that it’s topographical?

**Comment by maamari** [comment]
By default, I think there's a density parameter or something that shows up if you turn off the scatter hover and turn on the bivar hover. Idk if it can be overwritten, but if you can overwrite the bivar hover, you might be able to accomplish what you're looking for in this issue. Not trivial by any stretch though

**Comment by wen-jams** [comment]
For now, the filled bivar + scatter is enough. Additional features triggered by hover are planned, which will have their own issue posts. Closing this issue.
