### ISSUE TITLE
address memory leak when running plot cells repeatedly in JupyterLab

### ISSUE THREAD

**Issue by wen-jams** [wen-jams/bsavi#4]
look for garbage dump functions; consider running in classic Jupyter Notebook

**Comment by wen-jams** [comment]
seems like this is only a problem in the JupyterLab Desktop App. When running in jupyter notebook and jupyter in the browser, the memory usage stays stable. still should consider adding a plot.close() function or something like that

**Comment by maamari** [comment]
If you end up wanting to implement some sort of garbage collection, I've used [gc](https://docs.python.org/3/library/gc.html) in the past and it's easy to use and super effective. Weird that the issue only comes up in jupyterlab though

**Comment by wen-jams** [comment]
tried rerunning the plotting function a bunch of times and recording the memory usage in Edge:
![Screenshot 2023-04-09 215719](https://user-images.githubusercontent.com/40677090/230829216-a63bf01a-bbe7-4b75-8e7b-7c499afa2e69.png)

looks like the increase isn't that bad, and it isn't affecting the performance of the interactivity. also looks like this is already an issue with the Bokeh plotting backend:
[https://github.com/bokeh/bokeh/issues/8626](https://github.com/bokeh/bokeh/issues/8626)
