### ISSUE TITLE
alphas being reset to 1 when using linked brushing

### ISSUE THREAD

**Issue by wen-jams** [wen-jams/bsavi#5]
[linked brushing docs](https://holoviews.org/user_guide/Linked_Brushing.html#python-based-linked-brushing)

need to be able to see individual samples.

good:
![image](https://user-images.githubusercontent.com/40677090/188557186-1bbaf4e3-f0eb-437c-ad62-89bee1b82bcc.png)

bad:
![image](https://user-images.githubusercontent.com/40677090/188557309-91a77b6a-c829-4b53-ab74-9f0fa1da034e.png)

**Comment by maamari** [comment]
link table and scatter manually and overlay the bivar
